#!/bin/bash

export PATH=$PATH:/usr/games/

# If not running interactively, don't do anything
[[ $- != *i*  ]] && return

echo " @@@  @@@  @@@@@@@@              @@@@@@   @@@@@@@    @@@@@@@"
echo " @@@  @@@  @@@@@@@@             @@@@@@@@  @@@@@@@@  @@@@@@@@"
echo " @@!  @@@  @@!                  @@!  @@@  @@!  @@@  !@@"
echo " !@!  @!@  !@!                  !@!  @!@  !@!  @!@  !@!"
echo " @!@!@!@!  @!!!:!    @!@!@!@!@  @!@!@!@!  @!@!!@!   !@!"
echo " !!!@!!!!  !!!!!:    !!!@!@!!!  !!!@!!!!  !!@!@!    !!!"
echo " !!:  !!!  !!:                  !!:  !!!  !!: :!!   :!!"
echo " :!:  !:!  :!:                  :!:  !:!  :!:  !:!  :!:"
echo " ::   :::   :: ::::             ::   :::  ::   :::   ::: :::"
echo "  :   : :  : :: ::               :   : :   :   : :   :: :: :"
echo ""
echo ""
echo "   Please checkout the README.md file for all the details!"
echo ""
echo "                                                   Have fun!"

# Dull configuration
alias ls='ls --color=auto'
alias grep='grep --color=auto'
export EDITOR=nano
