# This file is only intended to be used for building the images.

version: '3'

services:

  base:
    image: hearcch/webapp-server:latest
    build:
      dockerfile: docker/base
      context: .
      # Set VCS/BUILD manually or use the Makefile.
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - MYSQL_VERSION=5.7
        - NODEJS_VERSION=9.x
        - POSTGRES_VERSION=9.6
        - TINI_VERSION=0.16.1
        - TINI_SIG=135f7342323526e39ba448c6ed5daab8f774430ce7887a3d562aa793e63dd99621b5251f80e5df8813fae0a3a3c041c646f0b0bf5455538d28a8f4b132aad190

  laravel:
    image: hearcch/webapp-server:laravel
    build:
      dockerfile: docker/laravel
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - PHP_VERSION=7.2

  rails:
    image: hearcch/webapp-server:rails
    build:
      dockerfile: docker/rails
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - RUBY_VERSION=2.4

  python:
    image: hearcch/webapp-server:python
    build:
      dockerfile: docker/python
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - PYTHON_VERSION=3.6
        - UWSGI_PLUGIN_NAME=36
