# This file is only intended to be used for building the images.

version: '3'

services:

  base:
    image: hearcch/webapp-server:latest
    build:
      dockerfile: docker/base
      context: .
      # Set VCS/BUILD manually or use the Makefile.
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - MYSQL_VERSION=5.7
        - NODEJS_VERSION=8.x
        - POSTGRES_VERSION=9.6
        - TINI_VERSION=0.14.0
        - TINI_SIG=816f84c4f17244f96e7c3063c74ae5ad8d3bf63722218b23863b73df5fae6d0430c02c0eea7d6d65c6c7a5f3453c3c736fd0ed96ac1f758974693705b3199039

  laravel:
    image: hearcch/webapp-server:laravel
    build:
      dockerfile: docker/laravel
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - PHP_VERSION=7.1

  rails:
    image: hearcch/webapp-server:rails
    build:
      dockerfile: docker/rails
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - RUBY_VERSION=2.4

  python:
    image: hearcch/webapp-server:python
    build:
      dockerfile: docker/python
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - PYTHON_VERSION=3.6
        - UWSGI_PLUGIN_NAME=36
