# This file is only intended to be used for building the images.

version: '3'

services:

  base:
    image: hearcch/webapp-server:latest
    build:
      dockerfile: docker/base
      context: .
      # Set VCS/BUILD manually or use the Makefile.
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
        - NODEJS_VERSION=16.x
        - UBUNTU_VERSION=focal

  laravel:
    image: hearcch/webapp-server:laravel
    build:
      dockerfile: docker/laravel
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE

  rails:
    image: hearcch/webapp-server:rails
    build:
      dockerfile: docker/rails
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE

  python:
    image: hearcch/webapp-server:python
    build:
      dockerfile: docker/python
      context: .
      args:
        - VCS_REF=$VCS_REF
        - BUILD_DATE=$BUILD_DATE
