version: '3.2'

services:
  admin:
    image: hearcch/webapp-server:latest
    environment:
      - GROUPNAME=admin
      - PASSWORD=root
      - SSH_KEYS=greut grunenwald
    hostname: admin
    volumes:
      - admin:/var/www
    ports:
      - "2222:22"
    external_links:
      - postgres
      - mysql
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.srvz-webapp.he-arc.ch`)"
      - "traefik.http.middlewares.admin-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.admin.middlewares=admin-redirect"
      - "traefik.http.routers.admin-secure.rule=Host(`admin.srvz-webapp.he-arc.ch`)"
      - "traefik.http.routers.admin-secure.entrypoints=https"
      - "traefik.http.routers.admin-secure.tls=true"
      - "traefik.http.routers.admin-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.admin-service.loadbalancer.server.port=80"

  admin_redis:
    image: redis:5-alpine
    volumes:
      - admin_redis:/data

networks:
  default:
    external:
      name: webapp-net

volumes:
  admin:
  admin_redis:
