version: '3.2'

services:
  eatapp:
    image: hearcch/webapp-server:laravel
    restart: always
    environment:
      - GROUPNAME=eatapp
      - PASSWORD=eatapp  # CHANGE ME
      - SSH_KEYS=greut grunenwald
    hostname: eatapp
    volumes:
      - eatapp:/var/www
    ports:
      - "2224:22"
    external_links:
      - postgres
      - mysql
      - smtp
    links:
      - eatapp_redis:redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eatapp.rule=Host(`eatapp.srvz-webapp.he-arc.ch`)"
      - "traefik.http.routers.eatapp.entrypoints=https"
      - "traefik.http.routers.eatapp.tls=true"
      - "traefik.http.routers.eatapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.eatapp-service.loadbalancer.server.port=80"

  eatapp_redis:
    image: redis:6-alpine
    volumes:
      - eatapp_redis:/data

networks:
  default:
    external: true
    name: webapp-net

volumes:
  eatapp:
  eatapp_redis:
