version: '3.2'

services:
  weblog:
    image: hearcch/webapp-server:python
    restart: always
    environment:
      - GROUPNAME=weblog
      - PASSWORD=root
      - SSH_KEYS=greut grunenwald
    hostname: python
    volumes:
      - weblog:/var/www
    ports:
      - "2223:22"
    external_links:
      - postgres
      - mysql
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weblog.rule=Host(`weblog.srvz-webapp.he-arc.ch`)"
      - "traefik.http.routers.weblog.entrypoints=https"
      - "traefik.http.routers.weblog.tls=true"
      - "traefik.http.routers.weblog.tls.certresolver=letsencrypt"
      - "traefik.http.services.weblog.loadbalancer.server.port=80"

  weblog_redis:
    image: redis:6-alpine
    volumes:
      - weblog_redis:/data

networks:
  default:
    external: true
    name: webapp-net

volumes:
  weblog:
  weblog_redis:
