version: '3.2'

services:
  capistrano:
    image: hearcch/webapp-server:rails
    restart: always
    environment:
      - GROUPNAME=capistrano
      - PASSWORD=capistrano  # CHANGE ME
      - SSH_KEYS=greut grunenwald osaris
    hostname: capistrano
    volumes:
      - capistrano:/var/www
    ports:
      - "2225:22"
    external_links:
      - postgres
      - mysql
      - smtp
    links:
      - capistrano_redis:redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.capistrano.rule=Host(`capistrano.srvz-webapp.he-arc.ch`)"
      - "traefik.http.middlewares.capistrano-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.capistrano.middlewares=capistrano-redirect"
      - "traefik.http.routers.capistrano-secure.rule=Host(`capistrano.srvz-webapp.he-arc.ch`)"
      - "traefik.http.routers.capistrano-secure.entrypoints=https"
      - "traefik.http.routers.capistrano-secure.tls=true"
      - "traefik.http.routers.capistrano-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.capistrano.loadbalancer.server.port=80"

  capistrano_redis:
    image: redis:4-alpine
    volumes:
      - capistrano_redis:/data

networks:
  default:
    external:
      name: webapp-net

volumes:
  capistrano:
  capistrano_redis:
