version: '3.2'

services:
  capistrano:
    image: hearcch/webapp-server:rails
    environment:
      - GROUPNAME=capistrano
      - PASSWORD=capistrano  # CHANGE ME
      - SSH_KEYS=greut grunenwald osaris
    hostname: capistrano
    volumes:
      - capistrano:/var/www
    ports:
      - "2225:22"
    external_links:
      - postgres
      - mysql
      - smtp
    links:
      - capistrano_redis:redis
    labels:
      - "traefik.frontend.rule=Host:capistrano.srvz-webapp.he-arc.ch"
      - "traefik.port=80"
      - "traefik.enable=true"

  capistrano_redis:
    image: redis:4-alpine
    volumes:
      - capistrano_redis:/data

networks:
  default:
    external:
      name: webapp-net

volumes:
  capistrano:
  capistrano_redis:
