#/bin/bash
{# vim: set ft=jinja: -#}

# If not running interactively, don't do anything
[[ $- != *i*  ]] && return

# So the files your create can be modified by the other members of your group.
umask 002

alias ls='ls --color=auto'
export EDITOR=vim
export GREP_OPTIONS='--color=auto'
{% for k, v in environ.items() -%}
export {{ k }}='{{ v }}'
{% endfor -%}
export PATH+=":/usr/games/:$HOME/.composer/vendor/bin"
export DEBIAN_FRONTEND=noninteractive

fortune | cowsay -f three-eyes
echo ""
toilet -f pagga -F border "webapp: {{ groupname }}"

echo ""
echo " Welcome {{ firstname }} {{ lastname }} ({{ classname }})!"
echo ""
echo " Please checkout the README.md file for all the details!"
echo ""
echo "                                                   Have fun!"
echo ""
