set nocompatible " required
filetype off     " required

" Set the runtime to include vundle and initialize it
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Your plugins
"Plugin 'bling/vim-airline'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-fugitive'
Plugin 'mv/mv-vim-nginx'
Plugin 'xsbeats/vim-blade'
Plugin 'othree/html5.vim'
Plugin 'chriskempson/base16-vim'
Plugin 'mrk21/yaml-vim'
Plugin 'kchmck/vim-coffee-script'

" All the plugins must be added before this
call vundle#end()         " required
filetype plugin indent on " required

" configuration
set colorcolumn=80,120
set undofile
set undodir=/tmp
set enc=utf8
set fenc=utf8

" 4 spaces instead of tabs
set ts=4
set sts=4
set sw=4
set expandtab

autocmd Filetype yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2 expandtab
autocmd Filetype eruby setlocal ts=2 sts=2 sw=2 expandtab

" Airline
"set laststatus=2
"let g:airline_powerline_fonts=1

" Theme
syntax enable
let base16colorspace=256
set background=dark
"colorscheme base16-default
"colorscheme base16-google
